"""empty message

Revision ID: e8a1dc5fff48
Revises: ad36a8cbabaa
Create Date: 2023-08-16 20:29:00.569415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8a1dc5fff48'
down_revision = 'ad36a8cbabaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address_book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address_book', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###
